limit: 1000
memory_size: 8192
memory_mapped_io:
  0x80: [ 4294967295, 0]
  0x84: []
reports:
  - name: "Result"
    slice: last
    view: "Output: {io:0x84:dec}"

  - name: "Execution trace"
    slice: all
    view: "{pc}: {instruction:next}"
