-- Drop tables
DROP TABLE IF EXISTS "prison_human" CASCADE;
DROP TABLE IF EXISTS "court_judge" CASCADE;
DROP TABLE IF EXISTS "factor_punishment" CASCADE;
DROP TABLE IF EXISTS "factor_accusation" CASCADE;
DROP TABLE IF EXISTS "relationships" CASCADE;
DROP TABLE IF EXISTS "event_people" CASCADE;
DROP TABLE IF EXISTS "wound" CASCADE;
DROP TABLE IF EXISTS "punishment" CASCADE;
DROP TABLE IF EXISTS "accusation" CASCADE;
DROP TABLE IF EXISTS "name" CASCADE;
DROP TABLE IF EXISTS "factor" CASCADE;
DROP TABLE IF EXISTS "court" CASCADE;
DROP TABLE IF EXISTS "event" CASCADE;
DROP TABLE IF EXISTS "prison" CASCADE;
DROP TABLE IF EXISTS "human" CASCADE;
DROP TABLE IF EXISTS "location" CASCADE;

-- Drop sequences
DROP SEQUENCE IF EXISTS location_id_seq CASCADE;
DROP SEQUENCE IF EXISTS human_id_seq CASCADE;
DROP SEQUENCE IF EXISTS prison_id_seq CASCADE;
DROP SEQUENCE IF EXISTS event_id_seq CASCADE;
DROP SEQUENCE IF EXISTS court_id_seq CASCADE;
DROP SEQUENCE IF EXISTS factor_id_seq CASCADE;
DROP SEQUENCE IF EXISTS accusation_id_seq CASCADE;
DROP SEQUENCE IF EXISTS punishment_id_seq CASCADE;
DROP SEQUENCE IF EXISTS wound_id_seq CASCADE;

-- Drop types
DROP TYPE IF EXISTS "prison_conditions" CASCADE;
DROP TYPE IF EXISTS "factor_type" CASCADE;
DROP TYPE IF EXISTS "accusation_type" CASCADE;
DROP TYPE IF EXISTS "punishment_type" CASCADE;
DROP TYPE IF EXISTS "event_role" CASCADE;
DROP TYPE IF EXISTS "event_consequence" CASCADE;
DROP TYPE IF EXISTS "relationship_type" CASCADE;
DROP TYPE IF EXISTS "location_climate" CASCADE;
